[tools]
node = "24"
npm = "latest"
pnpm = "latest"
yarn = "4"
bun = "latest"
deno = "2.4.2"
rust = "latest"
go = "latest"
python = "latest"
uv = "latest"
ghq = "latest"
"npm:@google/gemini-cli" = "latest"
"npm:markdownlint-cli" = "latest"
"npm:@devcontainers/cli" = "latest"
"npm:@openai/codex" = "latest"
"npm:cspell" = "latest"
"npm:typescript-language-server" = "latest"
"npm:svelte-language-server" = "latest"
"npm:@vue/language-server" = "latest"
"npm:@vtsls/language-server" = "latest"
"npm:@typescript/native-preview" = "latest"
"npm:vscode-langservers-extracted" = "latest"
"npm:vscode-css-languageservice" = "latest"
"npm:stylelint-lsp" = "latest"
"npm:cssmodules-language-server" = "latest"
"npm:@tailwindcss/language-server" = "latest"
"npm:bash-language-server" = "latest"
"npm:@actions/languageserver" = "latest"
"npm:yaml-language-server" = "latest"
"npm:@moonbit/moonbit-lsp" = "latest"
"npm:@ember-tooling/ember-language-server" = "latest"
"npm:chrome-devtools-mcp" = "latest"
"npm:fixjson" = "latest"
"npm:sql-formatter" = "latest"
"npm:sfw" = "latest"
"npm:editprompt" = "latest"
"npm:agent-browser" = "latest"
"go:github.com/nametake/golangci-lint-langserver" = "latest"
"go:github.com/sqls-server/sqls" = "latest"
"go:tailscale.com/cmd/tailscaled" = "main"
"go:tailscale.com/cmd/tailscale" = "main"
"go:golang.org/x/tools/gopls" = "latest"
"go:github.com/docker/docker-language-server/cmd/docker-language-server" = "latest"
"go:github.com/jesseduffield/lazydocker" = "latest"
"go:github.com/mattn/efm-langserver" = "latest"
"go:github.com/k1LoW/git-wt" = "latest"
"pipx:python-lsp-server" = "latest"
"pipx:markitdown" = { version = "latest", extras = "all" }
"pipx:plamo-translate" = "latest"
"pipx:markitdown-mcp" = "latest"
"pipx:awscli-local" = { version = "latest", extras = "ver1" }
"pipx:mdformat" = "latest"
"cargo:bacon" = { version = "latest", locked = true }
"cargo:tree-sitter-cli" = { version = "latest", locked = true }
"cargo:hyperfine" = { version = "latest", locked = true }
"cargo:zoxide" = { version = "latest", locked = true }
"cargo:ripgrep" = { version = "latest" }
"cargo:sheldon" = { version = "latest" }
"cargo:fd-find" = { version = "latest" }

[settings]
idiomatic_version_file_enable_tools = ["node"]
experimental = true

[settings.npm]
package_manager = "bun"
